name: create release

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: draft release
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/:repository/releases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INPUT_REPOSITORY: ${{ github.repository }}
          INPUT_TAG_NAME: ${{ github.event.pull_request.title }}
          INPUT_TARGET_COMMITISH: master
          INPUT_DRAFT: ${{ true }}
          INPUT_GENERATE_RELEASE_NOTES: ${{ true }}

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: "https://registry.npmjs.org"
          scope: "@darthrommy"
          always-auth: true
      - run: npm ci
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
